<?php

namespace AppBundle\Repository;

/**
 * AuditoriumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditoriumRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRows($id)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = '
        SELECT DISTINCT row FROM seats
        WHERE auditorium_id = :id
        ';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['id' => $id]);

        $result = $stmt->fetchAll();
        $rows = [];
        foreach ($result as $item)
        {
            $rows[] = $item['row'];
        }
        return $rows;
    }
}
