<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function count($criteria = []): int
    {
        $qb = $this->createQueryBuilder('r');

        return $qb->select('count(r.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
