<?php

namespace AppBundle\Repository;

/**
 * ReservedSeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservedSeatRepository extends \Doctrine\ORM\EntityRepository
{
}
