app:
    resource: '@AppBundle/Controller/'
    type: annotation

#Movies
movies:
    type: rest
    resource: AppBundle\Controller\MoviesController

movies_post:
    path: /movies
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\MoviesController::postMoviesAction
        _format: json

#Screenings
screenings:
    type: rest
    resource: AppBundle\Controller\ScreeningsController

screening_reserved_seats:
    path: /screenings/{screening}/reserved-seats
    methods: [GET]
    defaults:
        _controller: AppBundle\Controller\ScreeningsController::getScreeningReservedSeatsAction
        _format: json

#Auditoriums
auditoriums:
    type: rest
    resource: AppBundle\Controller\AuditoriumsController

auditoriums_post:
    path: /auditoriums
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\AuditoriumsController::postAuditoriumsAction
        _format: json

#Reservations
reservations:
    type: rest
    resource: AppBundle\Controller\ReservationsController

reservations_post:
    path: /reservations
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\ReservationsController:postReservationAction
        _format: json